### ISSUE TITLE
Workspace sharing not working on staging

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#499] opened 2020-06-12 10:26 UTC
I can't share any workspaces on staging. Can we make sure this is not impacting today's relase?

![image](https://user-images.githubusercontent.com/18245059/84493223-b8e8c580-aca7-11ea-910d-ed1276fc6e70.png)
https://herams-staging.org/workspace/5388/share

**Comment by SamMousa** [comment] 2020-06-12 13:13
Try now

**Comment by luna404** [comment] 2020-06-12 14:08
I still get an error with my account. Haven't tested with a non admin account yet.

**Comment by SamMousa** [comment] 2020-06-12 14:48
I think this is fixed now

**Comment by SamuelPetragallo** [comment] 2020-06-12 19:00
Have shared https://herams-staging.org/workspace/4893/share with user 10164 - user appears as "Deleted user" - can't revoke permissions, etc.

**Comment by SamMousa** [comment] 2020-06-12 19:36
You can revoke, i just did it..

**Comment by SamMousa** [comment] 2020-06-12 19:37
Also, the reported issue is not the same as the one you mention; so it does not belong here.

**Comment by SamMousa** [comment] 2020-06-12 19:37
Closing this since I have confirmed that it works..

**Closed by SamMousa** 2020-06-12 19:37 UTC
Labels: flow:works on staging, type:bug, urgency:high
