### ISSUE TITLE
Error in exporting GPS coordinates and Human Resources in HeRAMS Yemen (PROD AND STAGING)

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#517] opened 2020-06-16 17:25 UTC
Error in exporting dataset of HeRAMS Yemen wherein the latest record of a health facility have no responses for GPS Coordinates (MoSDGPS_SQ001, MoSDGPS_SQ002) and Human Resources (HFHR01_SQ006_SQ001, HFHR01_SQ002_SQ001, HFHR01_SQ003_SQ001, HFHR01_SQ004_SQ001, HFHR01_SQ005_SQ001, HFHR01_SQ001_SQ001) in STAGING AND PROD.

Responses appear in 1.) Our latest data and 2.) Our interpretation of the LS data and 3.) Data fresh from LS **BUT not in the "not in Response as it would be exported (but vertically)" and not in the downloaded data**

https://herams-staging.org/response/115562/compare?survey_id=618734

<img width="1280" alt="1Screen Shot 2020-06-17 at 1 19 46 AM" src="https://user-images.githubusercontent.com/50957748/84806936-10d15480-b039-11ea-8266-1037ac27f905.png">
<img width="1273" alt="2Screen Shot 2020-06-17 at 1 19 58 AM" src="https://user-images.githubusercontent.com/50957748/84806955-175fcc00-b039-11ea-9c30-2712983b39c0.png">
<img width="1521" alt="3Screen Shot 2020-06-17 at 1 15 36 AM" src="https://user-images.githubusercontent.com/50957748/84807038-35c5c780-b039-11ea-94a5-cda8b7563827.png">

**Comment by JeffDotingco** [comment] 2020-06-16 17:46
ID No: 118954 , SUBJECT ID: 171011 before WS refresh in PROD
<img width="956" alt="tESTScreen Shot 2020-06-16 at 8 40 15 PM (1)" src="https://user-images.githubusercontent.com/50957748/84809094-2b58fd00-b03c-11ea-8f49-7faaa1513c82.png">

ID No: 118954 , SUBJECT ID: 171011 after WS refresh in PROD:
<img width="1259" alt="TTESTScreen Shot 2020-06-16 at 8 41 39 PM" src="https://user-images.githubusercontent.com/50957748/84809176-49266200-b03c-11ea-86f3-af85f252929b.png">

**Comment by SamMousa** [comment] 2020-06-16 17:51
Hmm, the our latest data has a different format vs what it is supposed to be; the our interpretation of the LS data is what I'd expect to be in there.
After syncing the workspace the current data is in the correct format.

I'll have a look at the code pushing to HeRAMS to see if it uses a different format.

**Comment by JeffDotingco** [comment] 2020-06-17 11:11
Thanks @SamMousa, will test it in a bit.

**Comment by JeffDotingco** [comment] 2020-06-17 12:10
**Works in STAGING** (data validation in platform and downloaded data for HF with UOID: 2006015)

<img width="1680" alt="SATGINGScreen Shot 2020-06-17 at 8 02 38 PM" src="https://user-images.githubusercontent.com/50957748/84896229-28aae600-b0d6-11ea-91eb-6f179a69fc77.png">
![STAGING testing](https://user-images.githubusercontent.com/50957748/84896268-3ceee300-b0d6-11ea-9037-47fef20f1cdb.png)

**Not working in PROD** (data validation in platform and downloaded data for HF with UOID: 2006015)

<img width="1680" alt="PRODScreen Shot 2020-06-17 at 8 03 26 PM" src="https://user-images.githubusercontent.com/50957748/84896326-56902a80-b0d6-11ea-80ec-bebe70eef05f.png">
![PROD TESTING](https://user-images.githubusercontent.com/50957748/84896352-64de4680-b0d6-11ea-9f71-3ad0e4c88d88.png)

For further testing because I only tested one HF (UOID: 2006015) under WS  Dhamar / Wusab Al Ali

**Comment by SamMousa** [comment] 2020-06-17 12:14
For the case in PROD did you do an update of the record in LS first? Because I think it's working after you go through the LS submission.

(I just did that, no manual sync just completing the response and it seems to work)

**Comment by JeffDotingco** [comment] 2020-06-17 12:16
> For the case in PROD did you do an update of the record in LS first? Because I think it's working after you go through the LS submission.
> 
> (I just did that, no manual sync just completing the response and it seems to work)
I did not. Afraid to refresh. ;)

**Comment by JeffDotingco** [comment] 2020-06-17 12:30
PROD: GPS coordinates and HR responses are in the latest record for HF UOID 2006015:

<img width="1680" alt="Screen Shot 2020-06-17 at 8 25 27 PM" src="https://user-images.githubusercontent.com/50957748/84897756-b8519400-b0d8-11ea-811d-e52290dbf772.png">

<img width="1361" alt="7Screen Shot 2020-06-17 at 8 29 28 PM" src="https://user-images.githubusercontent.com/50957748/84898123-55acc800-b0d9-11ea-8350-79a642c0c40e.png">

**Comment by JeffDotingco** [comment] 2020-06-17 17:40
I tested this issue again by adding a record of Dharhan HU ( HF code: 2912028) of WS  Amran / Jabal Iyal Yazid with full submit the platform (PROD platform). The updated record is response ID 118979 and changed the HF name from  Dharhan HU to Dharhan HU (RECORD FOR TESTING -- 18 JUNE 2020). 

Then, I exported the dataset for the WS and the GPS coordinates and updated number of HR are reflected:
<img width="1644" alt="Screen Shot 2020-06-18 at 1 29 22 AM" src="https://user-images.githubusercontent.com/50957748/84930461-e5676c00-b103-11ea-8aaa-d50e8c146d34.png">

The data validation in the "Response as it would be exported (but vertically)" also verifies the updated responses: 

https://herams.org/response/118979/compare?survey_id=618734

<img width="1680" alt="Screen Shot 2020-06-18 at 1 36 33 AM" src="https://user-images.githubusercontent.com/50957748/84930643-2fe8e880-b104-11ea-87fc-a1e6aa474886.png">

The only observation weird is that the updated name of HF is not reflected in the platform but in the exported dataset, **Dharhan HU (RECORD FOR TESTING -- 18 JUNE 2020)** is already changed from **Dharhan HU**

**Comment by SamMousa** [comment] 2020-06-18 07:18
Then closing this since it has been resolved; open a new issue for the HF name if you can still reproduce it today.

**Comment by SamMousa** [comment] 2020-06-29 07:33
?

**Comment by JeffDotingco** [comment] 2020-06-29 07:33
Error still persists in PROD but not in STAGING upon checking.

https://herams.org/response/112330/compare?survey_id=618734
https://herams-staging.org/response/112330/compare?survey_id=618734


<img width="1680" alt="11_Screen Shot 2020-06-29 at 3 30 00 PM" src="https://user-images.githubusercontent.com/50957748/85985745-bb744a80-ba1d-11ea-8877-1f877a2ac534.png">

<img width="1680" alt="1_Screen Shot 2020-06-28 at 11 33 49 AM" src="https://user-images.githubusercontent.com/50957748/85985852-e9f22580-ba1d-11ea-8fe0-54784ec6de9c.png">

**Comment by luna404** [comment] 2020-06-29 12:58
removing the label as there still seems to be an issue on Prod.

**Closed** 2021-01-11 20:43 UTC
Labels: env:prod, env:staging, type:bug, wontfix
