### ISSUE TITLE
Prepare for SurveyJS

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#853] opened 2021-06-11 07:43 UTC
- [ ] Create a survey (db) model
- [ ] Integrate SurveyJS creator 
- [ ] Research if we need an update / create form, or if the SurveyJS creator suffices
- [ ] Research asset uploading in SurveyJS creator (for survey specific assets like images, if applicable)
- [ ] Research asset storage (DigitalOcean Spaces S3?)

**Comment by joester89** [comment] 2021-09-14 07:11
Duplicate of #885

**Closed by joester89** 2021-09-14 07:11 UTC
