### ISSUE TITLE
ls template / improvements

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#426] opened 2020-05-05 11:53 UTC
Adding a "header" with some basic information on the HF being edited:
1- Name / (UOID)
2- Type
3- GEO1

Others @luna404 @JeffDotingco ?

**Comment by luna404** [comment] 2020-05-22 13:34
I generally like the idea, but it might not be possible to this in LS.

I tried adding the type and name to the page header for Mali COVID. The problem is that we don't load all data at once but only the active page. In the case of Mali COVID, name and type are on page three of the questionnaire. This means the "header" will only show once you have loaded page 3.

You can try it out yourself here https://ls.herams.org/survey/index/sid/655873/token/123/lang/fr/newtest/Y

**Comment by JeffDotingco** [comment] 2020-05-22 13:44
Already implemented "Name of Health Facility: MoSD2" for HeRAMS YEM

**Comment by luna404** [comment] 2020-05-22 14:08
@JeffDotingco how are dealing with the fact that the MoSD2 variable is empty on the first two pages?

**Comment by SamMousa** [comment] 2020-05-23 09:20
@luna404  you could use `if` https://manual.limesurvey.org/Expression_Manager

Alternatively just print it (LS will print the empty string) and you can use CSS to hide show it if it's not empty.
```html
<span data-prefix="{htmlspecialchars(MoSD2.question)}" class="hf_name">{ MoSD2 }</span>
```

```css
.hf_name::before {
    content: attr('data-prefix');
}

.hf_name:empty() {
    display: none;
}
```

Note here I have used the question text of of MoSD2 to support localization for multi language surveys. It doesn't need to be the same question but could also be a different hidden one just to make the text configurable from within the survey interface (and thus translatable).

**Comment by luna404** [comment] 2020-11-19 13:01
As we are planning on moving to JS I will close this.

**Closed** 2021-05-28 07:48 UTC
Labels: subject:LS, type:not-platform, wontfix
