### ISSUE TITLE
Favorites not functioning for some users: "You are not allowed to perform this action"

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#437] opened 2020-05-07 12:31 UTC
Staging and Prod

Seems some users can't set favorites: test on staging for user 10688 (and others) doesn't allow the selection of WS and returns the above message when trying to access the list of favorites from the top banner

Seems there are limitations related to permissions. Don't think that using favorites should be restricted though

**Comment by SamMousa** [comment] 2020-05-07 12:32
Duplicate of #432, please search before creating new issues.

**Comment by SamuelPetragallo** [comment] 2020-05-07 12:32
Already reported by @jeremiehelme #430

**Closed by SamMousa** 2020-05-07 12:32 UTC
