### ISSUE TITLE
Standardization of question codes in the SDM

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#169] opened 2019-07-29 09:22 UTC
The aim of this issue is to consolidate all issues related to the standardization of HeRAMS question codes.

[Standard data model](https://drive.google.com/open?id=118OrRCl7WaDnM8Bc7rLyAwyEmTLNLo9y) latest version (2019-08-02)

**Comment by luna404** [comment] 2019-07-29 09:25
I added a few comments in the attached file. Also to better clarify the question type, I added a column specifying the question type

[HeRAMS_Standard_Data_Model_20190703_CF.docx](https://github.com/WorldHealthOrganization/herams-backend/files/3441254/HeRAMS_Standard_Data_Model_20190703_CF.docx)

**Comment by luna404** [comment] 2019-07-29 09:26
Trying to summarize the points made by Jeff

- [ ] HFACC1 is also a switching question that should be done in the questionnaire. All old surveys doesn’t have this condition so we need to verify and include it  where missing
- [] And also for MoSD4 (State / existence), but I will have this implemented for Cox’s once we have shown them the questionnaire and they agree. But for now, I haven’t implemented this yet.:)

**Comment by JeffDotingco** [comment] 2019-07-29 09:41
Logic for ranking questions:
minimum answers: 1
maximum answers: 3
maximum columns for answers: 3

(Some ranking questions doesn't follow the logic)

**Comment by FatmaGiha** [comment] 2019-07-29 09:46
To keep the "equipment part" mentioned in Q:HFINF1 on assessing the damage of the HFs, as a requirement raised by the World Bank. 
HFINF1: Condition of the health facility’s building and its essential equipment, in terms of infrastructural damages, whether is:
1.	Not damaged: intact building or insignificant damage
2.	Partially damaged: requiring substantial to large scale repair, but at a lower cost than a full reconstruction 
3.	Fully damaged: major damage requiring complete reconstruction, or extent of damage is such that costs to repair would be as high as the cost for reconstruction
4.     Not relevant: (e.g., mobile clinic)

**Comment by JeffDotingco** [comment] 2019-07-29 09:54
[HeRAMS_Cox's_Bazar_Data_Dictionary.pdf](https://github.com/WorldHealthOrganization/herams-backend/files/3441377/HeRAMS_Cox.s_Bazar_Data_Dictionary.pdf)

I have incorporated "REPAIR" and "Procurement" for the responses of CONDE: Equipment condition: Level of the damage of the equipment

**Comment by JeffDotingco** [comment] 2019-07-29 10:24
HFACC2:  "Not designed for people with limited mobility" not being added as a response

**Comment by JeffDotingco** [comment] 2019-07-29 10:33
[HeRAMS_Standard_Data_Model_20190703_CF_JBD.docx](https://github.com/WorldHealthOrganization/herams-backend/files/3441610/HeRAMS_Standard_Data_Model_20190703_CF_JBD.docx)

**Comment by FatmaGiha** [comment] 2019-07-29 12:43
> HFACC2: "Not designed for people with limited mobility" not being added as a response

Let us add it in the new surveys to be created, and consider revising answers options in the old projects when it is possible

**Comment by JeffDotingco** [comment] 2019-07-29 15:07
Caroline raised a point on basic amenities: number of functioning ambulances (this was included in Yemen) and cold chain (included in NGA). The number of functioning ambulances is relevant to PHL as this was raised by someone from MoH to be included. The cold chain is also important because this is the problem I foresee in PHL, a lot of HFs are only using kitchen refrigerators to store vaccine.

**Comment by JeffDotingco** [comment] 2019-07-29 15:12
Inpatient Capacity (Total No. of beds in wards): from the SDM, it is HFSUP5, but from other projects, it is HFINP1. If breakdown is essential, it should be HFBED1, HFBED2?:)

**Comment by JeffDotingco** [comment] 2019-07-29 15:21
HFBA5: Power Source, I suggest to change the response "3.	Solar system" to "Solar panel" or "Solar electricity". 

Agreeing with Caroline regarding the proper order of responses under Basic amenities of "No electricity" or "No communication equipment"  and "Others" for ease in the analysis.  "Others" should be in the last response. 

Another point raised by Caroline: Include internet under communication equipment type (HFBA7) as a response, agree.

**Comment by JeffDotingco** [comment] 2019-07-29 15:36
**Based on the Wiki : HeRAMS Systemic Variables**

Variables in ls that are expected in herams in all surveys:
1. HF Type: MoSD3
2. HF name: MoSD2 / implemented
3. HF functionality: HFFUNCT/ implemented
4. HF gps coordinates: Lat = MoSDGPS[SQ001] ; Long = MoSDGPS[SQ002] / not implemented
5. Location filter is reading from GEO1 / SM to confirm / not implemented in all surveys yet (GEO2-n are normally complementary text fields to record locations for which no stable standard is available e.g. sub-districts)
6. Also ensure each survey has an independent "submit" page at the end

**Comment by JeffDotingco** [comment] 2019-07-29 15:50
"Submit" question group already added (Pakistan, Sudan). @FatmaGiha kindly translate the group / question to Arabic. Shukran! :)

**Comment by FatmaGiha** [comment] 2019-07-30 15:45
> Inpatient Capacity (Total No. of beds in wards): from the SDM, it is HFSUP5, but from other projects, it is HFINP1. If breakdown is essential, it should be HFBED1, HFBED2?:)

Sometimes there is a breakdown for inpatient capacity; let us harmonise it all to be HFINP1, HFINP2,...etc

**Comment by FatmaGiha** [comment] 2019-07-30 16:06
> "Submit" question group already added (Pakistan, Sudan). @FatmaGiha kindly translate the group / question to Arabic. Shukran! :)

Done :) Afwan!

**Comment by FatmaGiha** [comment] 2019-07-30 17:11
Please check this SDM version, in which most of your feedback/ inputs are incorporated. I also replied to your comments where needed and inserted a couple of new ones.
Have a look and let me know your views... 

[HeRAMS_Standard_Data_Model_20190703_CF_JBD_FG.docx](https://github.com/WorldHealthOrganization/herams-backend/files/3448049/HeRAMS_Standard_Data_Model_20190703_CF_JBD_FG.docx)

**Comment by FatmaGiha** [comment] 2019-07-30 17:19
> Caroline raised a point on basic amenities: number of functioning ambulances (this was included in Yemen) and cold chain (included in NGA). The number of functioning ambulances is relevant to PHL as this was raised by someone from MoH to be included. The cold chain is also important because this is the problem I foresee in PHL, a lot of HFs are only using kitchen refrigerators to store vaccine.

Please note the availability of a functioning cold chain is linked with the availability of EPI service [monitored under **P2.1**]. Please check the list of HeRAMS services. See attached copy here.   
[HeRAMS_Services_Checklist.xlsx](https://github.com/WorldHealthOrganization/herams-backend/files/3448086/HeRAMS_Services_Checklist.xlsx)

If we are going to add the **ambulances**, I suggest to add it right after inpatient capacity and we ask about: Availability of functioning ambulances and Sufficiency

**Comment by JeffDotingco** [comment] 2019-07-31 03:47
Thanks for @FatmaGiha for this. I just edited some codes (MOSDGPS etc) and formatted the table a bit with the attached file. 

[HeRAMS_Standard_Data_Model_20190703_CF_JBD_FG_JBD.docx](https://github.com/WorldHealthOrganization/herams-backend/files/3449734/HeRAMS_Standard_Data_Model_20190703_CF_JBD_FG_JBD.docx)

**Comment by FatmaGiha** [comment] 2019-07-31 09:13
Thanks @JeffDotingco ... 
Regarding your comment “We are missing a section on HFSC: User Fees. From HeRAMS Sudan, this was under this section. “
 It was agreed before not to include user fees as a separate question; alternatively included s one of the main cause(s) for HFs’ inaccessibility [Physical barriers such as: broken bridges, flooded roads, and hard to reach places]

@luna404... Regarding your comment “Cold chain and availability of ambulances is not a mandatory basic amenity? (There included in several questionnaires but are not listed here)”
The availability of a functioning cold chain is linked to the availability of EPI service [P2.1]. Please check the list of HeRAMS services shared above, and let me if the feedback provided above is ok with you.

**Comment by FatmaGiha** [comment] 2019-07-31 12:49
@SamuelPetragallo to provide feedback to this query in SDM by @luna404, regarding the MoSD: 
The French questionnaires still use FOSA. Should this be changed to “modalités de prestation des services”?

**Comment by FatmaGiha** [comment] 2019-07-31 13:50
Hi all, 
Please check this cleaned version; especially the reshuffled component of (Date/ Update), which was previously under the MoSD section, and currently is considered as a separate component. 
[HeRAMS_Standard_Data_Model_20190731.docx](https://github.com/WorldHealthOrganization/herams-backend/files/3452125/HeRAMS_Standard_Data_Model_20190731.docx)

**Comment by JeffDotingco** [comment] 2019-08-01 08:45
Hi @FatmaGiha thanks a lot! Just rearrange the responses of HFBA7 (Communication Equipment type) into (order was different from definition and predefined answers):
1.	Telephone
2.	Fax
3.	Internet
4.	Not available
5.	Others (specify)

Also, "solar panel" and "solar system" were used in HFBA5. 

These are just very minor issues. :)

**Comment by SamMousa** [comment] 2019-08-01 09:41
Regarding question codes in the SDM, we should standardize casing as well:
```
MoSDGPS
Update
HFINF1
```

These 3 codes all use different rules.
I'd suggest to use all capitals or no capitals.

**Comment by FatmaGiha** [comment] 2019-08-01 21:01
> Regarding question codes in the SDM, we should standardize casing as well:
> 
> ```
> MoSDGPS
> Update
> HFINF1
> ```
> 
> These 3 codes all use different rules.
> I'd suggest to use all capitals or no capitals.

I have modified "Update" with "UPDATE", but for the MoSD and PoSD, it is the standard way we write them, so I left their related codes as it is. 
See updated document 
[HeRAMS_Standard_Data_Model_20190801.docx](https://github.com/WorldHealthOrganization/herams-backend/files/3458607/HeRAMS_Standard_Data_Model_20190801.docx)

**Comment by FatmaGiha** [comment] 2019-08-01 21:05
Can we change the title to: Standardization of data structure in the SDM instead of (Standardization of question codes in the SDM), because we are reviewing everything and not only codes

**Comment by SamMousa** [comment] 2019-08-01 21:30
From what standard? It makes sense to be consistent. Anyone can learn to use only capitals, and you will know what MOSDGPS means even it looks weird.

**Comment by SamMousa** [comment] 2019-08-01 21:30
The other way around is not true, anyone not familiar with those codes has no way of guessing which letters are capitals

**Comment by FatmaGiha** [comment] 2019-08-01 21:45
> From what standard? It makes sense to be consistent. Anyone can learn to use only capitals, and you will know what MOSDGPS means even it looks weird.

This is similar to the branding of HeRAMS (always to be written with a small e in the middle). This is what I meant by the standard way we write it. Coding of surveys' questions is done by us, so I don't see an issue of keeping the small "o" in the question code.

**Comment by SamMousa** [comment] 2019-08-02 07:21
The issue is not with the people who already know, the issue is with people who are new.
You want to have a few simple guidelines to construct question codes, with as few exceptions as possible.

A simple guideline is: use only capitals followed by numbers.

A complex guideline is:
- Use mostly just capitals
- Except with its an `o`,
- But `o` should be `O` when it's part of `COND`

The purpose of the SDM is not to tell people who already know, it is to be easy to grasp to people who do not know it.

**Comment by luna404** [comment] 2019-08-02 08:46
Thanks @FatmaGiha for all the work you put into this. It is very helpful 👍 

I just have minor comment on question HFBA7 ( Communication Equipment). Why is this a multiple choice question and not a ranking question? All the other questions in the BA section are ranking, so for consistency reasons, wouldn't it make more sense to have the same question type for all questions in the same section?

**Comment by FatmaGiha** [comment] 2019-08-02 09:26
Thanks @luna404 for spotting that out! 
This question was a multi-choice one, but to be consistent, Samuel and my self concurred to make it a Ranking question following the norm of the other BA questions. What you are referring to, is a typo, which was corrected in this version. 

[HeRAMS_Standard_Data_Model_20190802.docx](https://github.com/WorldHealthOrganization/herams-backend/files/3460548/HeRAMS_Standard_Data_Model_20190802.docx)

**Comment by luna404** [comment] 2019-08-07 07:27
I received an interesting feedback from Chad. In the BA section, if for example no electricity is available at a HF, users are still ask to enter whether there is is sufficient or insufficient electricity available. The colleagues in Chad noted that not available and insufficient are not the same thing. It is therefore misleading if users are forced to enter insufficient. 

Even though not available will always mean that there is insufficient I do agree with these guys that insufficient and none might make a big difference and should be differentiated. So my question, why are we not asking these questions the other way round. First ask if there is sufficient, insufficient or no electricity available. We can then make the questions regarding the types of electricity conditional on the answer and only show it if appropriate. This would also solve the current challenge that ranking question allow user to select for example "no electricity" and "generator" at the same time, which will causes issues analyzing the data.

**Comment by JeffDotingco** [comment] 2019-08-07 07:45
Agree with @luna404 on this one especially in analysing data. It is difficult to determine the number of HFs with the types of electricity being used (for example). If there is a question first on sufficient, insufficient and no electricity, followed by the ranking, it will be easy to analyse the BA part.

**Comment by FatmaGiha** [comment] 2019-08-07 10:14
The question on electricity (and similarly the other BAs questions) was initially asked in a form of specifying the main source, and “Not available” was one of the options. The type of question was a list (radio), not ranking. It was difficult to assess the case of irregular or partially available electricity, and here sufficiency was introduced to measure the satisfaction on the available level of electricity.   

@luna404 I do agree that ranking the answers, while “not available” option is there, is logically not correct, and also agree with your suggestion to: swap the questions: sufficiency comes first with 3 options [Yes, No, Not Available] then identification of sources [standard list of options except not available]. 
@SamuelPetragallo , if you like we can discuss it further in the meeting and conclude

**Comment by FatmaGiha** [comment] 2019-08-07 20:56
See attached the latest updated SDM file based on today’s discussions (i.e., amended and reshuffled the questions on Sufficiency and types of water sources, sanitation, power, and communication, under Basic amenities). 

[HeRAMS_Standard_Data_Model_20190807.docx](https://github.com/WorldHealthOrganization/herams-backend/files/3478843/HeRAMS_Standard_Data_Model_20190807.docx)

**Comment by JeffDotingco** [comment] 2019-08-09 09:28
Hi @FatmaGiha, I just edited the questions under basic amenities (e.g. Availability and sufficiency of communication equipment being used in the facility) and choices as well (i.e. Available and sufficient, Available but insufficient and Not available). I also made a comment on waste management, it is under environmental health of HeRAMS Mozambique. Updated SDM file attached.

[HeRAMS_Standard_Data_Model_20190807_JBD.docx](https://github.com/WorldHealthOrganization/herams-backend/files/3485655/HeRAMS_Standard_Data_Model_20190807_JBD.docx)

**Comment by FatmaGiha** [comment] 2019-08-09 12:54
Thank you @JeffDotingco, the Environment Health (EH) component was revised based on the WASH Guideline; revisions mainly included moving the Questions on water, sanitation, and waste management under BA section in alignment with WASH guideline. 
The point here is to treat WASH-related components as essential resources in the facility and not as health services, and accordingly remove the EH section from the services. Communications with HQ WASH team was established on this matter but not concluded yet, awaiting for their response.

**Comment by JeffDotingco** [comment] 2019-08-09 13:30
Thanks @FatmaGiha for the explanation, clear now from my end. :)

**Comment by FatmaGiha** [comment] 2019-08-26 12:40
Hello all, 
I am going through the SDM doc to make sure it is at the latest endorsed format by all of us, for sharing with other countries. While doing this, I came through the following points on reporting the damage of equipment, for your feedback: 

a) In the options of the “Level of damage to the essential equipment of the MoSD”, I removed the example of the (e.g. mobile clinic) from Not relevant, and wondering if we have examples where damage of equipment is irrelevant to be assessed for a MoSD? Otherwise, I suggest to remove that option here:  

**Level of damage to the essential equipment of the MoSD, whether it is:**
1.	Not damaged: or insignificant damage
2.	Partially damaged: requiring substantial repair of equipment or minimal replacement of equipment 
3.	Fully damaged: or major damage requiring complete replacement or procurement of new equipment 
4.	Not relevant

b) What if the building damage is reported partially or intact, while the equipment damage is reported as “fully damaged”? how this case will be treated- should the questionnaire stop?

**Comment by JeffDotingco** [comment] 2019-08-26 14:49
Hi @FatmaGiha, agree with removing e.g. Mobile Clinic to the equipment damage status and "fully damaged equipment" for the questionnaire to automatically stop by taking "flooding" in an area where the HF is located as an example.

**Comment by FatmaGiha** [comment] 2019-08-26 17:58
Thanks @JeffDotingco and @luna404  ... well received! 
Another point, I will modify where the questionnaire stops to be after reporting the causes of the "fully damage", not by selecting "fully damaged" only. What do you think?

**Comment by JeffDotingco** [comment] 2019-08-26 18:48
yes, the reasons of equipment damage should be asked first before automatic stop.

**Comment by luna404** [comment] 2019-08-27 07:36
Yes absolutely. 
Can we make a similar change for MoSD4 (MoSD State)? Especially if a facility is planned, I think it would be useful to get the GPS coordinates and the Structure type (MoSD5) before ending the questionnaire. What do you think?

**Comment by JeffDotingco** [comment] 2019-08-27 09:32
Agree with @luna404 . This happened in the initial configuration of HeRAMS Cox that I did not include MoSD4 because a lot of important data will not be considered that was already in the dataset. I just created another variable "other reasons for HFs to be non-functuioning". The MoSD4 (State) will be included once we touch base with in-country team.

**Comment by SamuelPetragallo** [comment] 2019-08-27 10:13
> Hello all,
> I am going through the SDM doc to make sure it is at the latest endorsed format by all of us, for sharing with other countries. While doing this, I came through the following points on reporting the damage of equipment, for your feedback:
> 
> a) In the options of the “Level of damage to the essential equipment of the MoSD”, I removed the example of the (e.g. mobile clinic) from Not relevant, and wondering if we have examples where damage of equipment is irrelevant to be assessed for a MoSD? Otherwise, I suggest to remove that option here:
> 
> **Level of damage to the essential equipment of the MoSD, whether it is:**
> 
> 1. Not damaged: or insignificant damage
> 2. Partially damaged: requiring substantial repair of equipment or minimal replacement of equipment
> 3. Fully damaged: or major damage requiring complete replacement or procurement of new equipment
> 4. Not relevant
> 
> b) What if the building damage is reported partially or intact, while the equipment damage is reported as “fully damaged”? how this case will be treated- should the questionnaire stop?

Agreed on a.

In case b. survey should continue I feel (there may in some very tiny structures still be some level of service, even if only consultation and "referral") that may take place while equipment is all out of order

**Comment by FatmaGiha** [comment] 2019-08-27 10:31
> Yes absolutely.
> Can we make a similar change for MoSD4 (MoSD State)? Especially if a facility is planned, I think it would be useful to get the GPS coordinates and the Structure type (MoSD5) before ending the questionnaire. What do you think?

Agree, and updated the remark on MoSD state to be: 
This is a switching question. If a MoSD is reported planned or closed, the questionnaire stops after completing the whole questions’ group of MoSD.

**Comment by FatmaGiha** [comment] 2019-08-27 10:33
> > Hello all,
> > I am going through the SDM doc to make sure it is at the latest endorsed format by all of us, for sharing with other countries. While doing this, I came through the following points on reporting the damage of equipment, for your feedback:
> > a) In the options of the “Level of damage to the essential equipment of the MoSD”, I removed the example of the (e.g. mobile clinic) from Not relevant, and wondering if we have examples where damage of equipment is irrelevant to be assessed for a MoSD? Otherwise, I suggest to remove that option here:
> > **Level of damage to the essential equipment of the MoSD, whether it is:**
> > 
> > 1. Not damaged: or insignificant damage
> > 2. Partially damaged: requiring substantial repair of equipment or minimal replacement of equipment
> > 3. Fully damaged: or major damage requiring complete replacement or procurement of new equipment
> > 4. Not relevant
> > 
> > b) What if the building damage is reported partially or intact, while the equipment damage is reported as “fully damaged”? how this case will be treated- should the questionnaire stop?
> 
> Agreed on a.
> 
> In case b. survey should continue I feel (there may in some very tiny structures still be some level of service, even if only consultation and "referral") that may take place while equipment is all out of order

Removed the condition for that question; the survey will flow normally if equipment is reported fully damaged

**Comment by FatmaGiha** [comment] 2019-08-27 10:44
@SamuelPetragallo , there is a citation for HeRAMS Guide in the SDM. I understood the title "HeRAMS Guide" will have to go through lengthy process of approval, so are we going to use an alternative name (like, HeRAMS Handbook) as discussed earlier? or we continue refernce the name HeRAMS Guide in the SDM? 
The updated SDM file is here: 
[HeRAMS_Standard_Data_Model_20190827.docx](https://github.com/WorldHealthOrganization/herams-backend/files/3545692/HeRAMS_Standard_Data_Model_20190827.docx)

**Comment by SamuelPetragallo** [comment] 2019-08-27 13:45
> @SamuelPetragallo , there is a citation for HeRAMS Guide in the SDM. I understood the title "HeRAMS Guide" will have to go through lengthy process of approval, so are we going to use an alternative name (like, HeRAMS Handbook) as discussed earlier? or we continue refernce the name HeRAMS Guide in the SDM?
> The updated SDM file is here:
> [HeRAMS_Standard_Data_Model_20190827.docx](https://github.com/WorldHealthOrganization/herams-backend/files/3545692/HeRAMS_Standard_Data_Model_20190827.docx)

Yes I was indeed told there may be issues there in terms of how we name this, as this may trigger some internal vetting process...

I suggest we highlight the name wherever present in the SDM (and other documents) so that we fix it when the guidance/handbook is finalized (and we've gone through the checks here)

**Comment by FatmaGiha** [comment] 2019-08-27 14:08
Thanks for the feedback.
I need to send the current SDM to Ethiopia, so in the meantime will refer to the name as **HeRAMS Guidebook**, until we concur on a final name.

**Comment by FatmaGiha** [comment] 2019-09-13 08:37
Hello @JeffDotingco  - Thank you for your observation and input. 
I think the outcome of this question is to measure how much partners are engaged in Provision of health services, so I see it not valid to include this option. If the partner's support is Provision of health staff, it means they are providing service given other factors are there as needed (medical supplies, operational cost, training...).
What do you think?

**Comment by JeffDotingco** [comment] 2019-09-13 08:51
Thanks @FatmaGiha, a good example for this is MSF, they provide health services to a POSD from a fixed HF or from a mobile clinic. I think this was raised also in Yemen and was requested by district health officers to be included (or provision of operational cost was the issue raised before).

**Comment by luna404** [comment] 2019-11-19 13:20
@FatmaGiha could we change the question codes for the BA section? I'm big fan of the question code logic used in other sections (e.g. CONDB CONDBx) as it allows to rapidly identify related questions simply using the question code. What do you think of expanding this logic to the BA section? For example instead of HFBA1 and HFBA2 we would use HFBA1 and HFBA1x.

**Comment by FatmaGiha** [comment] 2019-11-20 12:05
@luna404 I agree with your suggestion, and the example you provided (e.g. CONDB CONDBx) inspired me to change the other Questions' Codes pattern as well; e.g., instead of HFFUNCT to make it FUNCT only and simply the rest [AccessibilityManagement]. What do you think?  
Re the BAs and as discussed in the meeting we can make it more specific per type, e.g., INP1 (refers to inpatient capacity); BAW1 and BAWx (for sufficiency and sources respectively); BAS1 & BASx; BAWS1 & BAWSx; BASP1 & BASPx; BAIW1 & BAIWx; BAP1 & BAPx; BAC1 & BACx. 
It looks complicated I guess - I lost in letters :) maybe we should just do it as BA1 & BAx. What do you think?

**Comment by SamuelPetragallo** [comment] 2019-11-20 16:18
Agree overall to keep this "paring trick" throughout, but when doing this please make sure the prefix is identical- In the example above, BASP1 would give BASP1x - it's easier (I think) to automatically identify pairs that way: "qcode" with "x" suffix

**Comment by FatmaGiha** [comment] 2019-11-21 08:53
Well noted @SamuelPetragallo.
What about the other core questions, should I changes it... e.g., instead of HFFUNCT to make it FUNCT1

**Comment by SamuelPetragallo** [comment] 2019-11-21 09:17
Yes they can definitely be refined if needed (we've refined them constantly over the years) - we just need to ensure (ideally) that changes are reflected in ongoing survey so that we maintain consistency (thinking of report automation, etc.)

**Comment by FatmaGiha** [comment] 2019-11-21 09:25
Right! 
We can schedule that (updating the question's codes in the SDM) towards the end of the year if that's ok with the team.

**Comment by luna404** [comment] 2019-12-06 13:47
@FatmaGiha can we revert the section "Facility based Information Systems" back to use the old codes INOFX / INFOXx?
The current question codes (QHeRAMS) should only be used for service related questions (see issue #258 )

**Comment by FatmaGiha** [comment] 2019-12-06 14:46
Yes, I agree @luna404  
Previously, monitoring of available HISs was a section added at the last of the questionnaire (after the EH section), and when moved up (after designing the SDM) the question codes were just copied.  You are right it has to match the standard of the first sections.

**Comment by luna404** [comment] 2019-12-10 10:15
@FatmaGiha  as mentioned during the meeting today, here's the [link](https://ls.herams.org/admin/survey/sa/view/surveyid/783245/gid/695)to the new Chad questionnaire where I implemented new question codes for the BA section. I adapted the codes you proposed slightly to standardize the question code length for the this section.

**Comment by FatmaGiha** [comment] 2019-12-10 11:53
Thanks @luna404  -  well received. I adapted the codes of the BA section and Information systems following Chad's new questionnaire. Updated SDM attached. 

[HeRAMS_Standard_Data_Model_20191210.docx](https://github.com/WorldHealthOrganization/herams-backend/files/3944689/HeRAMS_Standard_Data_Model_20191210.docx)

**Closed** 2020-11-26 14:08 UTC
Labels: subject:documentation, wontfix
