### ISSUE TITLE
Admin pages: Workspace list - favorites column - no option to display all workspaces

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#770] opened 2021-01-27 16:16 UTC
The first value in the drop-down should be renamed to "all" or "show all" instead of being blank. Also once you filtered either by favorites or not favorites there is no way to go back to view all workspaces.

**Comment by SamMousa** [comment] 2021-01-28 15:23
Default UI for filters is that if they are not set everything is shown (the same for search boxes)

**Comment by luna404** [comment] 2021-01-29 10:14
Yes, but it's not clear for users that you can select an empty item. Also it doesn't work. If you select the empty list item it filters by non-favorites only.

**Comment by SamMousa** [comment] 2021-02-01 14:28
I've fixed the not working part, that wasn't intended.

In my opinion empty fields for not filtering is consistent with how filters work and it keeps the interface less cluttered initially.
The assumption is that if users select value in a dropdown they know to find the dropdown again to unselect something...

Anyway, I don't really care if you prefer to have a random `Show All` in the dropdown fields I can add it.. Just FYI, if users type 'Show all' in any of the text inputs, it will not show all. That won't be changed!

**Comment by SamMousa** [comment] 2021-02-12 13:57
Closing this since it now works as intended. Create a new issue if you insist on a label for not filtering.

**Closed by SamMousa** 2021-02-12 13:57 UTC
Labels: env:staging
