### ISSUE TITLE
Error refreshing WSs in PROD and STAGING 

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#454] opened 2020-05-18 02:29 UTC
Error refreshing WSs in PROD and STAGING. I tried Yemen, Cox's, PHL
<img width="1680" alt="Screen Shot 2020-05-18 at 10 22 53 AM" src="https://user-images.githubusercontent.com/50957748/82168857-5b549980-98f2-11ea-8da7-036962ca2f16.png">
<img width="1680" alt="Screen Shot 2020-05-18 at 10 29 01 AM" src="https://user-images.githubusercontent.com/50957748/82168890-6c050f80-98f2-11ea-8cfa-aeb2e8a5a738.png">

**Comment by SamMousa** [comment] 2020-05-18 05:33
Duplicate of #453

**Closed by SamMousa** 2020-05-18 05:33 UTC
