### ISSUE TITLE
Ability to invite users

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#662] opened 2020-11-18 10:03 UTC
user request: HeRAMS-WHO/herams-support#22

Brief description
Admins responsible to invite new users currently have to wait until a user has registered before they can assign permissions. This can be rather tedious for the admins as they can't assign permission in a single sessions and are dependent on users to register on time.

Expected behavior
If a user is not already register there should be an option for admins to invite a user. Once an invite has been sent, the admin should be able to assign permission even if the users has not yet confirmed their account.

**Comment by SamMousa** [comment] 2020-12-28 10:15
This will lead to an explosion of unused user accounts.
Currently the process is such that a user registration is only saved to the database after email confirmation.

The proposed flow is really sensitive to errors and will create strange experiences for users, for example:

1. I invite you to join, you don't get the mail (spam)
2. You try to sign up, it tells you account already exists

While I'm not necessarily opposed to admins inviting users (this fits within the current flow), having them assign permissions means we allow those admins to essentially create the users in our platform. These users then will not have confirmed email addresses and the owners of those email addresses may or may not be aware an account was created for them.

**Comment by SamMousa** [comment] 2020-12-28 10:17
Also, who decides what email address a user must use? What if you as an admin give me permissions on my secondary address but I have an account on my primary?

I feel this is disaster waiting to happen given the lack of technical expertise within our user group.

**Comment by luna404** [comment] 2021-01-04 09:13
`Also, who decides what email address a user must use? What if you as an admin give me permissions on my secondary address but I have an account on my primary?`

This issue already exists and in my opinion is not that big of a deal. Currently, the most common workflow is that admins in country have a list of names with an email address to go through and assign permissions. Identification of users is in the vast majority of cases done on email only as names are often too similar or users have multiple names and they use different name when they register compared to what the country focal point has in their list. Thus, the risk of users creating multiple accounts already exists. However, having the ability to invite users would be a huge help for the country admins. The back and forth of getting 100+ users registered in order to assign them permissions takes a lot of time and in my opinion is waste of time.

**Comment by SamMousa** [comment] 2021-01-04 12:27
Wouldn't a proper request permission flow solve the extra work instead?

That way account creation is decentralized and workspace admins only have to "accept" a request.

**Comment by luna404** [comment] 2021-01-05 09:26
Why not both?

**Comment by SamMousa** [comment] 2021-01-05 09:28
Because admins will make a mess of our user registration, and they can do it in bigger batches. 
It will cause the system to send unsolicited mails in batches which means higher spam rates... The arguments against this feature stay the same. The better request flow could alleviate the work of admins without introducing the errors.

**Comment by SamMousa** [comment] 2021-01-12 09:18
Solution:
Create invite new user form on share page.
- The user will be automatically granted permission when the account has been created
- Add the subject to favorites

**Comment by SamMousa** [comment] 2021-01-26 09:17
- There will be no overview of invited users
- Links will only be valid for 7 days

**Comment by joester89** [comment] 2021-03-16 15:03
@luna404 @SamuelPetragallo

It is time to test :)
The testenvironment can be found here: https://feature-662-invite-users.herams-staging.org

How it currently works:
- Go to the share page of either a project, workspace or even global admin
- Type the emailadres of the new user and select the new email address
- Select the desired permissions and click add

Now an email will be sent to the new user. In that email there is a link with which the user can create an account. The first step is to select the desired email address. If changed, a new email will be sent to assure the email address does exist. The link of that mail is the same as continuing without changing the email address. Now the user sees the form which is about the same as the create user form.

After finalizing the user will be granted the given permissions on the resource.

Important notes:
- Only permissions to 1 resource can be given in parallel. I.e. you add an emailaddress to project 1 with permission x, and before the user accepted it you also add the same emailaddress to project 2 with permission y. For both an email will be sent (since we do not track all the invitations) and only one of both can be accepted.
- If a user by accident types an email address of a user that already exists instead of selecting, this case will be handled correctly and no email will be sent.

**Comment by SamMousa** [comment] 2021-03-16 15:05
> only one of both can be accepted.

Can't we just give them the permission when they click the second one?

**Comment by joester89** [comment] 2021-03-16 15:07
> > only one of both can be accepted.
> 
> Can't we just give them the permission when they click the second one?
> (after requiring them to log in)

That could be an interesting extension!

**Comment by luna404** [comment] 2021-03-16 17:16
This is great, it works well if I only assign a single permission but it seems to have an issue if you assign multiple permissions. 

For example, this is the invitation link

https://feature-662-invite-users.herams-staging.org/user/accept-invitation?email=fuhrca00%40gmail.com&subject=prime%5Cmodels%5Car%5CWorkspace&subjectId=7683&permissions=update-data%2Ccreate-facility%2Cexport%2Cshare%2Csuper-share%2CROLE_LEAD&e=1616518879&h=3jOm_nPjpZwpbk6r9Qv2VJXu0d3SMHCso9xWvRyyGwU

I have no problem creating the account but I don't have any of the above permissions. If you go to the share page of this workspace, the new user appears in the list of existing users but without any permissions. 

https://feature-662-invite-users.herams-staging.org/workspace/7683/share
![image](https://user-images.githubusercontent.com/18245059/111351222-3dc39e00-8683-11eb-9791-4eca6eed8a76.png)

**Comment by joester89** [comment] 2021-03-17 09:49
@luna404 this should be fixed now

**Comment by joester89** [comment] 2021-03-17 14:40
@luna404 2 new things have been added:
- when a user clicks the link while begin logged in, there now is the option to accept the invitation
- a link cannot be reused, when a user clicks next or accepts the invitation when logged in the link will be blocked

**Comment by luna404** [comment] 2021-03-23 10:19
I'm not able to accept an invitation if I'm already logged in with that account. If I try to accept the invitation I get an error that the email is already in use.

![image](https://user-images.githubusercontent.com/18245059/112131063-6d196400-8bc9-11eb-9d11-29aa72834d0b.png)

**Comment by joester89** [comment] 2021-03-23 11:45
@luna404 should be fixed now

**Comment by luna404** [comment] 2021-03-23 13:25
Thanks, it's working now.

One more question, after creating a new account the user is not automatically logged in but is redirected to the standard login page. Is this on purpose?
Same if you already have an account but opt to create a new account. It keeps you logged in with the old account. Wouldn't make more sense for the user to either be logged out or logged in automatically with the newly created account?

**Comment by joester89** [comment] 2021-03-24 08:09
@luna404 I made it consistent with the create user flow. There you aren't logged in automatically as well.

Als changing the logged in person would be strange in my opinion. We could add more buttons giving the user the explicit choice or add an explanation of what will happen if we get feedback on this?

**Comment by luna404** [comment] 2021-03-29 11:55
Noted. As this is a rather unique case anyways, let's leave it as is for now.

**Closed** 2021-04-06 08:31 UTC
Labels: User Priority, flow:approved, flow:works on staging, type:enhancement, urgency:normal
