### ISSUE TITLE
Timestamps when access requests where granted are wrong

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#943] opened 2021-11-11 08:08 UTC
The timestamps when access requests are granted are wrong. See the screenshot below. 

https://herams.org/access-request/index?access-request-provider-sort=-responded_at
![image](https://user-images.githubusercontent.com/18245059/141261177-a0981c18-55bc-4695-8b42-6e45db5cc1cd.png)

**Comment by joester89** [comment] 2021-11-11 08:47
Why are they wrong? What would you expect then?

**Comment by luna404** [comment] 2021-11-11 08:58
Cause today is Nov. 11th and they show that they were approved on Nov. 25th 2021 which is two weeks from now.

**Comment by SamMousa** [comment] 2021-11-16 08:54
@joester89 interesting cause:
1. We use `->touch()` which is provided by `TimestampBehavior`
2. We used to use 2 `TimestampBehavior` (one for create / update and one for expires), so it'd pick the first one. 
3. We removed the first behavior for audit log, so it then uses the remaining one, which has a value 2 weeks in the future.

Solution:
- Implement touch via trait.

**Comment by SamMousa** [comment] 2021-11-16 09:00
On second thought, since other attributes change too, I'm just moving this to a normal attribute update and removing the call to tocuh.

**Comment by SamMousa** [comment] 2021-11-16 09:58
@luna404 this has been fixed; but the issue is actually in what is written to the database. So after the fix is released you'll be seeing correct dates when requests get updated, until then it'll be off by 2 weeks.

**Comment by SamMousa** [comment] 2021-11-24 10:19
@luna404 this should now also work correctly for any new actions taken on prod. Please confirm and close if that's the case.

**Closed** 2022-01-11 09:24 UTC
Labels: type:bug, urgency:normal
